[project]
name = "Hypersonic"
version = "0.1.0"
description = "Hypersonic local runner"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "embasp-python>=8.1.3",
    "flake8>=7.2.0",
    "pygame>=2.6.1",
]
